### ISSUE TITLE
Getting an import error

### ISSUE THREAD

**Issue by xircon** [ncmiller/roku-cli#3]
Installed with pip.
```
roku
Traceback (most recent call last):
  File "/usr/bin/roku", line 7, in <module>
    from rokucli.cli import main
  File "/usr/lib/python3.5/site-packages/rokucli/cli.py", line 4, in <module>
    from discover import discover_roku
ImportError: No module named 'discover'
```

**Comment by ncmiller** [comment]
@xicon - Thanks for the bringing this to my attention. I just pushed version 1.0.1 to PyPI, so if you don't mind trying the install again, it should work.

**Comment by xircon** [comment]
New error:
```
roku                      
Searching for Roku devices within LAN ...
Found the following Roku devices:
Traceback (most recent call last):
  File "/usr/bin/roku", line 11, in <module>
    load_entry_point('rokucli==1.0.1', 'console_scripts', 'roku')()
  File "/usr/lib/python3.5/site-packages/rokucli/cli.py", line 135, in main
    RokuCLI().run()
  File "/usr/lib/python3.5/site-packages/rokucli/cli.py", line 89, in run
    self.roku = discover_roku()
  File "/usr/lib/python3.5/site-packages/rokucli/discover.py", line 18, in discover_roku
    dinfo = ' '.join(re.split(', |: ', str(r.device_info))[1:3])
  File "/usr/lib/python3.5/site-packages/roku/core.py", line 89, in __getattr__
    raise AttributeError('%s is not a valid method' % name)
AttributeError: device_info is not a valid method
```

**Comment by xircon** [comment]
This is what I am working on - https://github.com/xircon/Simple-roku-remote-pyqt4-
Looking for a better way to discover roku, any ideas?
Think I have found one, but is late here.......

**Comment by ncmiller** [comment]
Well, I fixed the device_info issue, but not quite the way I wanted. I removed device_info altogether since it relies on a feature of python-roku that isn't yet released to PyPI. 

So if you want to try to reinstall from pip (now on v1.0.4), it should work (I hope).

**Comment by xircon** [comment]
Cheers, now working.
